### ISSUE TITLE
To combine in a command: USERLIST and PROFILE-FULL

### ISSUE THREAD

**Issue by DavidPerea** [haccer/twint#124]
After the great new update that includes this command: `--profile-full`   I have used it with an user and it works. However, when I wanted to **add more users** with the command, `--userlist` ,    it does not return anything.

I mean, this command does not work.
`python Twint.py --userlist user1,user2 --profile-full -o file.csv --csv`

Could this problem be solved? even so the new update is wonderful.

**Comment by pielco11** [comment]
This will require a lot of time since it's "serializing" the requests, first for user1 than for user2 and so on...

It can be considered time-saving running searches in different process, could be even more interesting and powerful running in a "multithreading" mode but now this is not deployed yet. 

We will work on it

**Comment by DavidPerea** [comment]
Of course I understand it. I imagined it would be a very laborious job.

No problem. I was to comment on it.

Anyway thank you very much. Your work is being very useful.
