### ISSUE TITLE
Geolocation data

### ISSUE THREAD

**Issue by DonaldTsang** [haccer/twint#56]
It would be great to have geolocation as part of the columns

**Comment by haccer** [comment]
Column for csv?

**Comment by haccer** [comment]
Doesn't seem like a way to fetch location from Tweets within the search, are you meaning when you specify geolocation as a search you would like that stored in the column?

**Comment by DonaldTsang** [comment]
@haccer not as a search function, but as a new attribute stored in a column

**Comment by michael-ab** [comment]
Yes, it would be really useful to store location, even for all requests to be able to create a map with Kibana.

**Comment by haccer** [comment]
I'm trying to think of a good way to do this. 

If I were to add it in, to collect the location data you would need to send a request to **every** tweet.. which is a lot of requests.

**Comment by haccer** [comment]
I didn't think I was going to be able to add this since Twitter has removed the location a person's at from appearing in the Tweet; so we're getting the location data from their Twitter profile... which is sometimes not as accurate, but it's better than nothing. It's a bit slower than a regular search, but same speed as getting a person's favorites is.
