### ISSUE TITLE
Since and until together

### ISSUE THREAD

**Issue by panoptikum** [haccer/twint#66]
Hey There,

Thanks for this great code repository!

the following command captures tweets older than 1st December 2017. Is my command wrong?

### Command
python3 twint.py -s metoo -l de -o test2.csv --csv --unt 2017-12-02 --since 2017-12-01

### Description of Issue
Combination of since and until does not work

### OS Details
Mac OS

Cheers,
Felix

**Comment by pielco11** [comment]
The `until` arg is `--until`.

By the way, there were two problems, the first is that `timedelta` was bigger than the difference of the `until` and `since`, now this is fixed and if the difference is more than 30 days, the timedelta is 30 days.

The second one is that Twitter does not respond well with given args, for example what @panoptikum is getting can be found [here](https://twitter.com/search?f=tweets&vertical=default&l=de&lang=en&q=%20metoo%20since%3A2017-12-01%20until%3A2017-12-02) (twitter search link) and if you scroll down you can see that there are tweets of 30th Nov 2017, so this part of the problem is not with twint.

I "fixed" (read mitigated) the problem adding an if condition while getting the tweet and now it works as we want.

**Comment by pielco11** [comment]
The mitigation applied for this issue is not compatible with another type of usage. If one is looking for tweets `until` 2017-10-02 and he/she does not specify the `since` arg, it will be `until` - 30 days and twint will update this time interval every once is needed, and this is fine. 

But if one is looking for `until` 2017-10-02 and `since` 2017-10-01 he/she will get some tweets since           2017-09-30 because Twitter search is giving results that we are not expecting. A solution for this could be "don't handle these tweets" but this is not compatible with the above mentioned situation because, with the corresponding time range, some tweets will be filtered out by the mitigation applied. 

So to have the most compatible setup for every situation, now as now, we have to get every tweets that Twitter is giving the "clean up" at ended search/tweets retrieve (this is not ready yet). At least this is what sounds in my mind.

**Comment by pielco11** [comment]
@panoptikum now twint should work as expected (at least it tried and everything seems right)

**Comment by panoptikum** [comment]
@pielco11 Thanks for your quick response. I was also relatively sure that I specified it correctly in the past. I'll check, if it works now and report back here.

**Comment by pielco11** [comment]
#84

**Comment by pielco11** [comment]
#164
