### ISSUE TITLE
Append to csv/file on update

### ISSUE THREAD

**Issue by blind0wl** [haccer/twint#73]
Is there a way to instead of running the script and it downloading and saving output to a file each time, we can just append the latest tweets into the file?  Some way of comparing what we have versus what we're missing?

Thanks

**Comment by pielco11** [comment]
Hi and thanks for the hint, now as now you can use the `since` and `until` args to filter out a specific date range and so use the `until` arg of the day before of the latest tweet. The day before because you may not have been able to download all the tweets of the "latest day".

Until we don't provide a solution for your situation I suggest you to proceed in that way, hope this helps.
